# Generated by Django 4.0.4 on 2022-06-17 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_Number', models.IntegerField()),
                ('Amount_Paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Number_Of_Nights', models.IntegerField()),
                ('Day_Of_Arrival', models.DateField()),
                ('Day_Of_Departure', models.DateField()),
                ('Name_Of_Occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.personalinformation')),
            ],
        ),
    ]
