# Generated by Django 4.0.4 on 2022-06-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_hotelrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HotelRecord',
        ),
        migrations.DeleteModel(
            name='PersonalInformation',
        ),
    ]
